# Generated by Django 3.2.10 on 2021-12-18 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?[0-9]{10}$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
